CREATE TABLE BOOKING (
                       ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                       CABIN_ID INTEGER NOT NULL,
                       START DATE NOT NULL,
                       UNTILL DATE NOT NULL,
                       CREATED_AT TIMESTAMP NOT NULL,
                       UPDATED TIMESTAMP,
                       PRIMARY KEY (ID)
);

ALTER TABLE BOOKING ADD FOREIGN KEY (CABIN_ID) REFERENCES CABIN(ID);

-- Bokningar för Stor-stugan
INSERT INTO BOOKING (CABIN_ID, START, UNTILL, CREATED_AT)
VALUES ((SELECT ID FROM CABIN WHERE NAME = 'Big-cabin'), '2025-02-01', '2025-02-05', CURRENT_DATE);

INSERT INTO BOOKING (CABIN_ID, START, UNTILL, CREATED_AT)
VALUES ((SELECT ID FROM CABIN WHERE NAME = 'Big-cabin'), '2025-02-10', '2025-02-15', CURRENT_DATE);

INSERT INTO BOOKING (CABIN_ID, START, UNTILL, CREATED_AT)
VALUES ((SELECT ID FROM CABIN WHERE NAME = 'Big-cabin'), '2025-02-20', '2025-02-25', CURRENT_DATE);

-- Bokningar för Mellan-stugan
INSERT INTO BOOKING (CABIN_ID, START, UNTILL, CREATED_AT)
VALUES ((SELECT ID FROM CABIN WHERE NAME = 'Middle-cabin'), '2025-02-11', '2025-02-19', CURRENT_DATE);

INSERT INTO BOOKING (CABIN_ID, START, UNTILL, CREATED_AT)
VALUES ((SELECT ID FROM CABIN WHERE NAME = 'Middle-cabin'), '2025-02-21', '2025-02-28', CURRENT_DATE);

-- Bokningar för Lill-stugan
INSERT INTO BOOKING (CABIN_ID, START, UNTILL, CREATED_AT)
VALUES ((SELECT ID FROM CABIN WHERE NAME = 'Lil-cabin'), '2025-02-01', '2025-02-21', CURRENT_DATE);


